name: Luacheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Install luacheck
      run:  luarocks install luacheck

    - name: Execute luacheck
      run: luacheck lua
