# This is a basic workflow to help you get started with Actions

name: Deploy docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
                
      - name: Install Lua/LuaJIT
        # You may pin to the exact commit or the version.
        # uses: leafo/gh-actions-lua@ea0ae38722c0b45aa4e770f7c4a650c6b26800d0
        uses: leafo/gh-actions-lua@v8.0.0
    
      - name: Install LuaRocks
        # You may pin to the exact commit or the version.
        # uses: leafo/gh-actions-luarocks@218573cd14f9a47b079c9b89349f9b71cb5ee706
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install ldoc
        run: |
          luarocks install ldoc

      - name: Update to latest canvas-lms-lua
        run: |
          [ -d "canvas-lms-lua" ] && (cd canvas-lms-lua/; git checkout master; git pull) || git clone https://github.com/wspr/canvas-lms-lua/ canvas-lms-lua
          cd canvas-lms-lua
          git config user.email "noreply@wspr.io"
          git config user.name  "Will Robertson's robot"
          git checkout gh-pages
          git rebase master

      - name: Run ldoc
        run: |
          cd canvas-lms-lua
          ldoc lua/
          
      - name: Push to gh-pages branch
        run: |
          cd canvas-lms-lua
          git add doc/*
          git commit -m "doc update"
          git push -f
          
         
